### ISSUE TITLE
科学上网（SSR）自建教程

### ISSUE THREAD

**Issue by stx8991** [stx8991/stx8991#9]
- 第一步·拥有一个能访问外网的VPS

- 第二步·安装SSR服务端
1.` yum -y install wget`

2. `wget https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocksR.sh`

3.`chmod +x shadowsocksR.sh`

4.`/shadowsocksR.sh 2>&1 | tee shadowsocksR.log`

- 上面的代码要一行一行的执行执行完最后一行后，会出现下面的截图

> 设置连接密码

![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/3437998107.png)

> 设置访问端口

![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/1646232942.png)

设置加密方式

![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/3886036725.png)

设置协议插件

![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/2073725575.png)

设置混淆插件
x>如果协议是origin，那么混淆也必须是plain；如果协议不是origin，那么混淆可以是任意的。有的地区需要把混淆设置成plain才好用。因为混淆不总是有效果，要看各地区的策略，有时候不混淆（plain）或者（origin和plain一起使用），让其看起来像随机数据更好。（特别注意：tls 1.2_ticket_auth容易受到干扰！请选择除tls开头以外的其它混淆！！！）

![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/1402450799.png)

完成，查看连接信息
![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/2853325353.png)

> 重要的信息记在下面

 

> 想要卸载的话就执行

`./shadowsocksR.sh uninstall`
 

> 如果忘记了连接信息请执行

`cat shadowsocksR.log`

> 如果想查看运行状态请执行

`/etc/init.d/shadowsocks status`

> 如果想重启ssr请执行

`/etc/init.d/shadowsocks restart`

> 如果想停止请执行

`/etc/init.d/shadowsocks stop`

>  如果想启动请执行

`/etc/init.d/shadowsocks start`
第三步·安装SSR客户端（起飞）
接下来是下载客户端  动动小手在下面评论一下就可以直接下载咯
这个绿色的是客户端哦，评论即可下载呢！ 下载速度超快的，因为是自己的网盘，没有限速哦！

windows版：
此处内容需要评论回复后（审核通过）方可阅读。
MAC版：
此处内容需要评论回复后（审核通过）方可阅读。
启动4.0的exe文件

![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/200442094.png)

编辑服务器

![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/328033350.png)

输入参数
只要输入我框的就行了，然后确认

![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/1563867194.png)

![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/283660169.png)

最后的设置

![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/2077157320.png)

第四步·访问谷歌试试吧
![](https://blog-salivawar.oss-cn-beijing.aliyuncs.com/www_salivawar_com/usr/uploads/2019/11/1153698773.png)

完成

**Comment by 349989153** [comment]
SSR现在还管用？
